module.exports = conversoesSchema = 'CREATE TABLE IF NOT EXISTS `conversoes` '
                    + '('
                    + '`id` INT AUTO_INCREMENT PRIMARY KEY,'
                    + '`usuarioid` int NOT NULL,'
                    + '`moedaid` VARCHAR(255) NOT NULL,'
                    + '`moedanome` VARCHAR(255) NOT NULL,'
                    + '`quantidade` decimal NOT NULL,'
                    + '`precobrl` VARCHAR(255) NOT NULL,'
                    + '`precousd` VARCHAR(255) NOT NULL,'
                    + 'FOREIGN KEY (usuarioid) REFERENCES usuarios(id),'
                    + 'FOREIGN KEY (moedaid) REFERENCES moedastop100(id)'
                    + ')'